### PR TITLE
Removed code duplicate in StackedHorizontalProgressBar.java class. Ad…

### PR DESCRIPTION
**Pull request by mayojava**
Removed code duplicate in StackedHorizontalProgressBar.java class. Added an `init()` function which is called from both `constructors`.

### CODE REVIEW

**Comment by nisrulz** [comment]
@mayojava instead of calling it through some private function `init()`, you should be doing that by calling constructors. 

Its a small change , but I see you want to contribute, so maybe change your PR to be like this

``` java
 public StackedHorizontalProgressBar(Context context) {
     paint = new Paint();
     paint.setColor(Color.BLACK);
     primary_progress = 0;
     max_value = 100;
    }

    public StackedHorizontalProgressBar(Context context, AttributeSet attrs) {
     super(context, attrs);
     // Use the first constructor code here
     this(context);
    }
```

**Comment by mayojava** [comment]
great @nisrulz. I will make the change, but if we are not calling `super(context)` from the constructor that takes the `context`, then it means we can use that constructor in java code

**Comment by nisrulz** [comment]
@mayojava hmm..you are right, my mistake. I missed that in there. Merging your code 😄

**Comment by mayojava** [comment]
Great @nisrulz . Thanks. I think we can close the issue now :)

**Pull request merged**
